In [2]:
import pandas as pd

In [4]:
data = {
    'Name': ['Gopal',"Ram","Sham"],
    'Age' : [22,21,22],
    'City' : ["Tandur","Unknown","Unknown"] 
}


df = pd.DataFrame(data)

print(df)

    Name  Age     City
0  Gopal   22   Tandur
1    Ram   21  Unknown
2   Sham   22  Unknown

In [5]:
df['Salary'] = [0,'NULL','NULL']

df

    Name  Age     City Salary
0  Gopal   22   Tandur      0
1    Ram   21  Unknown   NULL
2   Sham   22  Unknown   NULL

In [8]:
data_2 = [
    {'Name' : 'Gopal','Age' : 22},
    {'Name' : "Shyam",'Age' : 'Unknown'}
]

# df2

# for record in data_2:
#     record['Salary'] = 1000

df2 = pd.DataFrame(data_2)
df2['Salary'] = [0,'1000']
print(df2)

    Name      Age Salary
0  Gopal       22      0
1  Shyam  Unknown   1000

## Data Manipulation using Pandas

In [3]:
df = pd.read_csv('data.csv')

# To fetch the first and last few rows
print(df.head(5), "\n")
print(df.tail(5))

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [11]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   29.000000
mean    68.437500  103.500000  128.500000  306.451724
std     70.039591    7.832933   12.998759   66.442116
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  300.000000
75%     60.000000  106.500000  132.250000  345.300000
max    450.000000  130.000000  175.000000  479.000000

In [12]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [5]:
# Hanlding Missing Values

df.isnull().any(axis = 1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22     True
23     True
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
dtype: bool

In [7]:
df.isnull().sum()

Duration    0
Date        2
Pulse       0
Maxpulse    0
Calories    3
dtype: int64

In [9]:
df.fillna(0)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134       0.0
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       0.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45             0    100       119     282.0
23        60             0    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       0.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [13]:
# Fill the Missing Values in Calories with the mean of the Calories.

df.fillna(df['Calories'].mean())

    Duration          Date  Pulse  Maxpulse    Calories
0         60  '2020/12/01'    110       130  409.100000
1         60  '2020/12/02'    117       145  479.000000
2         60  '2020/12/03'    103       135  340.000000
3         45  '2020/12/04'    109       175  282.400000
4         45  '2020/12/05'    117       148  406.000000
5         60  '2020/12/06'    102       127  300.000000
6         60  '2020/12/07'    110       136  374.000000
7        450  '2020/12/08'    104       134  306.451724
8         30  '2020/12/09'    109       133  195.100000
9         60  '2020/12/10'     98       124  269.000000
10        60  '2020/12/11'    103       147  329.300000
11        60  '2020/12/12'    100       120  250.700000
12        60  '2020/12/12'    100       120  250.700000
13        60  '2020/12/13'    106       128  345.300000
14        60  '2020/12/14'    104       132  379.300000
15        60  '2020/12/15'     98       123  275.000000
16        60  '2020/12/16'     98       120  215.200000
17        60  '2020/12/17'    100       120  300.000000
18        45  '2020/12/18'     90       112  306.451724
19        60  '2020/12/19'    103       123  323.000000
20        45  '2020/12/20'     97       125  243.000000
21        60  '2020/12/21'    108       131  364.200000
22        45    306.451724    100       119  282.000000
23        60    306.451724    130       101  300.000000
24        45  '2020/12/24'    105       132  246.000000
25        60  '2020/12/25'    102       126  334.500000
26        60      20201226    100       120  250.000000
27        60  '2020/12/27'     92       118  241.000000
28        60  '2020/12/28'    103       132  306.451724
29        60  '2020/12/29'    100       132  280.000000
30        60  '2020/12/30'    102       129  380.300000
31        60  '2020/12/31'     92       115  243.000000

In [ ]:
# Fill the Missing Values of Calories with the Mean of Calories into a new Column

df['Sales_fillna'] = df['Calories'].fillna(df['Calories'].mean())

df

    Duration          Date  Pulse  Maxpulse  Calories  Sales_fillna
0         60  '2020/12/01'    110       130     409.1    409.100000
1         60  '2020/12/02'    117       145     479.0    479.000000
2         60  '2020/12/03'    103       135     340.0    340.000000
3         45  '2020/12/04'    109       175     282.4    282.400000
4         45  '2020/12/05'    117       148     406.0    406.000000
5         60  '2020/12/06'    102       127     300.0    300.000000
6         60  '2020/12/07'    110       136     374.0    374.000000
7        450  '2020/12/08'    104       134       NaN    306.451724
8         30  '2020/12/09'    109       133     195.1    195.100000
9         60  '2020/12/10'     98       124     269.0    269.000000
10        60  '2020/12/11'    103       147     329.3    329.300000
11        60  '2020/12/12'    100       120     250.7    250.700000
12        60  '2020/12/12'    100       120     250.7    250.700000
13        60  '2020/12/13'    106       128     345.3    345.300000
14        60  '2020/12/14'    104       132     379.3    379.300000
15        60  '2020/12/15'     98       123     275.0    275.000000
16        60  '2020/12/16'     98       120     215.2    215.200000
17        60  '2020/12/17'    100       120     300.0    300.000000
18        45  '2020/12/18'     90       112       NaN    306.451724
19        60  '2020/12/19'    103       123     323.0    323.000000
20        45  '2020/12/20'     97       125     243.0    243.000000
21        60  '2020/12/21'    108       131     364.2    364.200000
22        45           NaN    100       119     282.0    282.000000
23        60           NaN    130       101     300.0    300.000000
24        45  '2020/12/24'    105       132     246.0    246.000000
25        60  '2020/12/25'    102       126     334.5    334.500000
26        60      20201226    100       120     250.0    250.000000
27        60  '2020/12/27'     92       118     241.0    241.000000
28        60  '2020/12/28'    103       132       NaN    306.451724
29        60  '2020/12/29'    100       132     280.0    280.000000
30        60  '2020/12/30'    102       129     380.3    380.300000
31        60  '2020/12/31'     92       115     243.0    243.000000

In [20]:
# Renaming Columns
df = df.rename(columns={'Maxpulse':'Max-Pulse'})
df.head()

   Duration          Date  Pulse  Max-Pulse  Calories  Sales_fillna
0        60  '2020/12/01'    110        130     409.1         409.1
1        60  '2020/12/02'    117        145     479.0         479.0
2        60  '2020/12/03'    103        135     340.0         340.0
3        45  '2020/12/04'    109        175     282.4         282.4
4        45  '2020/12/05'    117        148     406.0         406.0

In [ ]:
df.dtypes

Duration          int64
Date             object
Pulse             int64
Max-Pulse         int64
Calories        float64
Sales_fillna    float64
dtype: object

In [ ]:

#Changing the Data type of the column

df['Calories_New'] = df['Calories'].fillna(df['Calories'].mean()).astype(int)

df

,Duration,Date,Pulse,Max-Pulse,Calories,Sales_fillna,Calories_New
0,60,'2020/12/01',110,130,409.1,409.100000,409
1,60,'2020/12/02',117,145,479.0,479.000000,479
2,60,'2020/12/03',103,135,340.0,340.000000,340
3,45,'2020/12/04',109,175,282.4,282.400000,282
4,45,'2020/12/05',117,148,406.0,406.000000,406
5,60,'2020/12/06',102,127,300.0,300.000000,300
6,60,'2020/12/07',110,136,374.0,374.000000,374
7,450,'2020/12/08',104,134,NaN,306.451724,306
8,30,'2020/12/09',109,133,195.1,195.100000,195
9,60,'2020/12/10',98,124,269.0,269.000000,269
10,60,'2020/12/11',103,147,329.3,329.300000,329
11,60,'2020/12/12',100,120,250.7,250.700000,250
12,60,'2020/12/12',100,120,250.7,250.700000,250
13,60,'2020/12/13',106,128,345.3,345.300000,345
14,60,'2020/12/14',104,132,379.3,379.300000,379
15,60,'2020/12/15',98,123,275.0,275.000000,275
16,60,'2020/12/16',98,120,215.2,215.200000,215
17,60,'2020/12/17',100,120,300.0,300.000000,300
18,45,'2020/12/18',90,112,NaN,306.451724,306
19,60,'2020/12/19',103,123,323.0,323.000000,323
20,45,'2020/12/20',97,125,243.0,243.000000,243
21,60,'2020/12/21',108,131,364.2,364.200000,364
22,45,NaN,100,119,282.0,282.000000,282
23,60,NaN,130,101,300.0,300.000000,300
24,45,'2020/12/24',105,132,246.0,246.000000,246
25,60,'2020/12/25',102,126,334.5,334.500000,334
26,60,20201226,100,120,250.0,250.000000,250
27,60,'2020/12/27',92,118,241.0,241.000000,241
28,60,'2020/12/28',103,132,NaN,306.451724,306
29,60,'2020/12/29',100,132,280.0,280.000000,280
30,60,'2020/12/30',102,129,380.3,380.300000,380
31,60,'2020/12/31',92,115,243.0,243.000000,243

In [ ]:
# Apply a function

df['Pulse*2'] = df['Pulse'].apply(lambda x:x * 2)
df

,Duration,Date,Pulse,Max-Pulse,Calories,Sales_fillna,Calories_New,Pulse*2
0,60,'2020/12/01',110,130,409.1,409.100000,409,220
1,60,'2020/12/02',117,145,479.0,479.000000,479,234
2,60,'2020/12/03',103,135,340.0,340.000000,340,206
3,45,'2020/12/04',109,175,282.4,282.400000,282,218
4,45,'2020/12/05',117,148,406.0,406.000000,406,234
5,60,'2020/12/06',102,127,300.0,300.000000,300,204
6,60,'2020/12/07',110,136,374.0,374.000000,374,220
7,450,'2020/12/08',104,134,NaN,306.451724,306,208
8,30,'2020/12/09',109,133,195.1,195.100000,195,218
9,60,'2020/12/10',98,124,269.0,269.000000,269,196
10,60,'2020/12/11',103,147,329.3,329.300000,329,206
11,60,'2020/12/12',100,120,250.7,250.700000,250,200
12,60,'2020/12/12',100,120,250.7,250.700000,250,200
13,60,'2020/12/13',106,128,345.3,345.300000,345,212
14,60,'2020/12/14',104,132,379.3,379.300000,379,208
15,60,'2020/12/15',98,123,275.0,275.000000,275,196
16,60,'2020/12/16',98,120,215.2,215.200000,215,196
17,60,'2020/12/17',100,120,300.0,300.000000,300,200
18,45,'2020/12/18',90,112,NaN,306.451724,306,180
19,60,'2020/12/19',103,123,323.0,323.000000,323,206
20,45,'2020/12/20',97,125,243.0,243.000000,243,194
21,60,'2020/12/21',108,131,364.2,364.200000,364,216
22,45,NaN,100,119,282.0,282.000000,282,200
23,60,NaN,130,101,300.0,300.000000,300,260
24,45,'2020/12/24',105,132,246.0,246.000000,246,210
25,60,'2020/12/25',102,126,334.5,334.500000,334,204
26,60,20201226,100,120,250.0,250.000000,250,200
27,60,'2020/12/27',92,118,241.0,241.000000,241,184
28,60,'2020/12/28',103,132,NaN,306.451724,306,206
29,60,'2020/12/29',100,132,280.0,280.000000,280,200
30,60,'2020/12/30',102,129,380.3,380.300000,380,204
31,60,'2020/12/31',92,115,243.0,243.000000,243,184