In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('Sales_April_2019.csv')
data.head(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18383 entries, 0 to 18382
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          18324 non-null  object
 1   Product           18324 non-null  object
 2   Quantity Ordered  18324 non-null  object
 3   Price Each        18324 non-null  object
 4   Order Date        18324 non-null  object
 5   Purchase Address  18324 non-null  object
dtypes: object(6)
memory usage: 861.8+ KB

In [5]:
data.shape

(18383, 6)

In [6]:
data.isnull().sum()

Order ID            59
Product             59
Quantity Ordered    59
Price Each          59
Order Date          59
Purchase Address    59
dtype: int64

In [7]:
data_copy = data
data_copy

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [8]:
data_copy = data_copy.dropna(how='all')

In [9]:
data_copy.head(5)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

In [10]:
data_copy.isnull().sum()

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

In [11]:
data_copy.shape

(18324, 6)

In [12]:
# Converting the Date,month,year format into separate columns
data_copy[['Date','Month','Year']] = data_copy['Order Date'].str.split('/',expand=True)

C:\Users\gopal\AppData\Local\Temp\ipykernel_26292\346173615.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_copy[['Date','Month','Year']] = data_copy['Order Date'].str.split('/',expand=True)
C:\Users\gopal\AppData\Local\Temp\ipykernel_26292\346173615.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_copy[['Date','Month','Year']] = data_copy['Order Date'].str.split('/',expand=True)
C:\Users\gopal\AppData\Local\Temp\ipykernel_26292\346173615.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_copy[['Date','Month','Year']] = data_copy['Order Date'].str.split('/',expand=True)

In [13]:
data_copy

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Date,Month,Year
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",04,19,19 08:46
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",04,07,19 22:30
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",04,12,19 14:38
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",04,12,19 14:38
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",04,30,19 09:27
...,...,...,...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001",04,08,19 17:11
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301",04,15,19 16:02
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016",04,28,19 14:36
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035",04,14,19 15:09
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215",04,18,19 11:08

In [14]:
data_copy[['Year','Time']] = data_copy['Year'].str.split(' ',expand=True)

C:\Users\gopal\AppData\Local\Temp\ipykernel_26292\2365806567.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_copy[['Year','Time']] = data_copy['Year'].str.split(' ',expand=True)
C:\Users\gopal\AppData\Local\Temp\ipykernel_26292\2365806567.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_copy[['Year','Time']] = data_copy['Year'].str.split(' ',expand=True)

In [15]:
data_copy

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Date,Month,Year,Time
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",04,19,19,08:46
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",04,07,19,22:30
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",04,12,19,14:38
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",04,12,19,14:38
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",04,30,19,09:27
...,...,...,...,...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001",04,08,19,17:11
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301",04,15,19,16:02
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016",04,28,19,14:36
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035",04,14,19,15:09
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215",04,18,19,11:08

In [31]:
# data_copy.info()
# data_copy['Date'].isnull().sum()
# data_copy.head(3)
# for col in ['Date','Month','Year']:
#     print(f"\nInvalid values in {col}:")
#     print(data_copy[~data_copy[col].astype(str).str.isnumeric()][col].unique())

(data_copy['Date'] == 'Order Date').sum()

np.int64(35)

In [33]:
removed_rows = data_copy[data_copy['Date'] == 'Order Date']
# data_copy = da

removed_rows

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Date,Month,Year,Time
519,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
1149,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
1155,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
2878,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
2893,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
3036,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
3209,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
3618,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
4138,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
4645,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
4794,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
5303,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
6939,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
7497,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
8635,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
9189,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
9329,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
9973,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
10885,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
10958,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
11272,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
11619,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
11742,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
11778,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
11874,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
12455,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
13362,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
14022,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
14522,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
14860,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
15280,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
17208,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
17324,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
17339,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None
17744,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Order Date,None,None,None

In [ ]:
data_copy = data_copy[data_copy['Date'] != 'Order Date'].reset_index(drop=True)
# data_copy.shape

Empty DataFrame
Columns: [Order ID, Product, Quantity Ordered, Price Each, Order Date, Purchase Address, Date, Month, Year, Time]
Index: []

In [40]:
data_copy['Date'] = data_copy['Date'].astype('int')
data_copy['Month'] = data_copy['Month'].astype('int')
data_copy['Year'] = data_copy['Year'].astype('int')
# data_copy['Date']

data_copy

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Date,Month,Year,Time
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001",4,19,19,08:46
1,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215",4,7,19,22:30
2,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",4,12,19,14:38
3,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001",4,12,19,14:38
4,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001",4,30,19,09:27
...,...,...,...,...,...,...,...,...,...,...
18284,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001",4,8,19,17:11
18285,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301",4,15,19,16:02
18286,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016",4,28,19,14:36
18287,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035",4,14,19,15:09
18288,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215",4,18,19,11:08

In [42]:
data_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18289 entries, 0 to 18288
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          18289 non-null  object
 1   Product           18289 non-null  object
 2   Quantity Ordered  18289 non-null  object
 3   Price Each        18289 non-null  object
 4   Order Date        18289 non-null  object
 5   Purchase Address  18289 non-null  object
 6   Date              18289 non-null  int64
 7   Month             18289 non-null  int64
 8   Year              18289 non-null  int64
 9   Time              18289 non-null  object
dtypes: int64(3), object(7)
memory usage: 1.4+ MB

In [45]:
data_copy = data_copy.drop('Order Date',axis=1)

In [50]:
data_copy
# removed_rows

,Order ID,Product,Quantity Ordered,Price Each,Purchase Address,Date,Month,Year,Time
0,176558,USB-C Charging Cable,2,11.95,"917 1st St, Dallas, TX 75001",4,19,19,08:46
1,176559,Bose SoundSport Headphones,1,99.99,"682 Chestnut St, Boston, MA 02215",4,7,19,22:30
2,176560,Google Phone,1,600,"669 Spruce St, Los Angeles, CA 90001",4,12,19,14:38
3,176560,Wired Headphones,1,11.99,"669 Spruce St, Los Angeles, CA 90001",4,12,19,14:38
4,176561,Wired Headphones,1,11.99,"333 8th St, Los Angeles, CA 90001",4,30,19,09:27
...,...,...,...,...,...,...,...,...,...
18284,194090,Google Phone,1,600,"177 Jackson St, Los Angeles, CA 90001",4,8,19,17:11
18285,194091,AA Batteries (4-pack),1,3.84,"311 Forest St, Austin, TX 73301",4,15,19,16:02
18286,194092,AAA Batteries (4-pack),2,2.99,"347 Sunset St, San Francisco, CA 94016",4,28,19,14:36
18287,194093,AA Batteries (4-pack),1,3.84,"835 Lake St, Portland, OR 97035",4,14,19,15:09
18288,194094,Lightning Charging Cable,1,14.95,"354 North St, Boston, MA 02215",4,18,19,11:08

In [51]:
data_copy['Hours'] = data_copy['Time'].str.split(':').str[0]
data_copy['Minutes'] = data_copy['Time'].str.split(':').str[1]

In [55]:
data_copy = data_copy.drop('Time',axis=1)

In [57]:
data_copy['Hours'] = data_copy['Hours'].astype('int')
data_copy['Minutes'] = data_copy['Minutes'].astype('int')

In [61]:
data_copy

,Order ID,Product,Quantity Ordered,Price Each,Purchase Address,Date,Month,Year,Hours,Minutes
0,176558,USB-C Charging Cable,2,11.95,"917 1st St, Dallas, TX 75001",4,19,19,8,46
1,176559,Bose SoundSport Headphones,1,99.99,"682 Chestnut St, Boston, MA 02215",4,7,19,22,30
2,176560,Google Phone,1,600,"669 Spruce St, Los Angeles, CA 90001",4,12,19,14,38
3,176560,Wired Headphones,1,11.99,"669 Spruce St, Los Angeles, CA 90001",4,12,19,14,38
4,176561,Wired Headphones,1,11.99,"333 8th St, Los Angeles, CA 90001",4,30,19,9,27
...,...,...,...,...,...,...,...,...,...,...
18284,194090,Google Phone,1,600,"177 Jackson St, Los Angeles, CA 90001",4,8,19,17,11
18285,194091,AA Batteries (4-pack),1,3.84,"311 Forest St, Austin, TX 73301",4,15,19,16,2
18286,194092,AAA Batteries (4-pack),2,2.99,"347 Sunset St, San Francisco, CA 94016",4,28,19,14,36
18287,194093,AA Batteries (4-pack),1,3.84,"835 Lake St, Portland, OR 97035",4,14,19,15,9
18288,194094,Lightning Charging Cable,1,14.95,"354 North St, Boston, MA 02215",4,18,19,11,8

In [64]:
data_copy.nunique()

Order ID            17537
Product                19
Quantity Ordered        7
Price Each             18
Purchase Address    17119
Date                    2
Month                  30
Year                    1
Hours                  24
Minutes                60
dtype: int64